/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.sisoperativos.gui;

import javax.swing.*;
import java.awt.*;

/**
 *
 * @author gabri
 */
public class CpuChart extends JPanel {

    private double[] history = new double[50];
    private int puntosActuales = 0;

    /**
     * Creates new form CpuChart
     */
    public CpuChart() {
        this.setBackground(new Color(20, 20, 20));
        this.setPreferredSize(new Dimension(400, 250));
    }

    public void addPoint(double utilization) {
        if (puntosActuales < history.length) {
            history[puntosActuales] = utilization;
            puntosActuales++;
        } else {
            for (int i = 0; i < history.length - 1; i++) {
                history[i] = history[i + 1];
            }
            history[history.length - 1] = utilization;
        }
        repaint();
    }

    @Override
    protected void paintComponent(Graphics g) {
        super.paintComponent(g);
        Graphics2D g2 = (Graphics2D) g;
        g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);

        int w = getWidth();
        int h = getHeight();

        // Dibujar rejilla verde oscuro
        g2.setColor(new Color(40, 60, 40));
        for (int i = 0; i <= 10; i++) {
            g2.drawLine(0, i * h / 10, w, i * h / 10);
            g2.drawLine(i * w / 10, 0, i * w / 10, h);
        }

        if (puntosActuales < 2) {
            return;
        }

        // Dibujar la línea Cian
        g2.setColor(Color.CYAN);
        g2.setStroke(new BasicStroke(2f));

        for (int i = 0; i < puntosActuales - 1; i++) {
            int x1 = i * (w / (history.length - 1));
            int y1 = h - (int) (history[i] * h / 100);
            int x2 = (i + 1) * (w / (history.length - 1));
            int y2 = h - (int) (history[i + 1] * h / 100);
            g2.drawLine(x1, y1, x2, y2);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
