package com.mycompany.sisoperativos.gui;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
import com.mycompany.sisoperativos.logic.Clock;
import com.mycompany.sisoperativos.logic.PCB;
import com.mycompany.sisoperativos.logic.Scheduling;
import com.mycompany.sisoperativos.logic.Queue;
import com.mycompany.sisoperativos.logic.Process;

import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author gabri
 */
public class Dashboard extends javax.swing.JFrame {

    // Instancias de tu motor
    private Scheduling scheduler;
    private Clock simClock;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Dashboard.class.getName());

    /**
     * Creates new form Dashboard
     */
    public Dashboard() {
        initComponents(); // Carga la ventana

        // 1. Inicializamos tu motor
        scheduler = new Scheduling(this);
        scheduler.setPolitic("FCFS"); // O la política que quieras

        // 2. Metemos un par de procesos de prueba a la cola
        PCB p1 = new PCB();
        p1.setId(101);
        p1.setDurationR(10);
        p1.setPriority(1);
        p1.setDeadlineR(20);
        scheduler.getReadyQueue().enqueueFIFO(p1);

        PCB p2 = new PCB();
        p2.setId(202);
        p2.setDurationR(5);
        p2.setPriority(5);
        p2.setDeadlineR(10);
        scheduler.getReadyQueue().enqueueFIFO(p2);

        // 3. ¡IMPORTANTE! Creamos el reloj y le pasamos "this" (esta ventana)
        simClock = new Clock(1000, scheduler, this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblReloj = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        txtCpuId = new javax.swing.JLabel();
        txtCpuRem = new javax.swing.JLabel();
        txtCpuPriority = new javax.swing.JLabel();
        txtCpuDL = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaListos = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tablaBloqueados = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtConsola = new javax.swing.JTextArea();
        btnIniciar = new javax.swing.JButton();
        random = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tablaSalida = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblReloj.setText("lblReloj");

        jPanel2.setBackground(new java.awt.Color(100, 242, 242));

        txtCpuId.setBackground(new java.awt.Color(242, 242, 100));
        txtCpuId.setText("txt");

        txtCpuRem.setBackground(new java.awt.Color(242, 242, 100));
        txtCpuRem.setText("rem");

        txtCpuPriority.setBackground(new java.awt.Color(242, 242, 100));
        txtCpuPriority.setText("priority");

        txtCpuDL.setBackground(new java.awt.Color(242, 242, 100));
        txtCpuDL.setText("dead");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(txtCpuId, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCpuDL, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtCpuPriority, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCpuRem, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(44, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(txtCpuId)
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(txtCpuDL)
                        .addGap(10, 10, 10)))
                .addComponent(txtCpuRem)
                .addGap(18, 18, 18)
                .addComponent(txtCpuPriority)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(242, 100, 242));

        tablaListos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "CPU Restante", "Prioridad", "Deadline"
            }
        ));
        jScrollPane1.setViewportView(tablaListos);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jPanel5.setBackground(new java.awt.Color(242, 100, 242));

        tablaBloqueados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "CPU Restante", "Prioridad", "Deadline"
            }
        ));
        jScrollPane3.setViewportView(tablaBloqueados);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        txtConsola.setColumns(20);
        txtConsola.setRows(5);
        jScrollPane2.setViewportView(txtConsola);

        btnIniciar.setText("jButton1");
        btnIniciar.addActionListener(this::btnIniciarActionPerformed);

        random.setText("random");
        random.addActionListener(this::randomActionPerformed);

        jPanel6.setBackground(new java.awt.Color(242, 100, 242));

        tablaSalida.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "CPU Restante", "Prioridad", "Deadline"
            }
        ));
        jScrollPane4.setViewportView(tablaSalida);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 392, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblReloj, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnIniciar)
                        .addGap(67, 67, 67)
                        .addComponent(random)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 387, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(104, 104, 104))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(89, 89, 89))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblReloj, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnIniciar)
                    .addComponent(random))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 79, Short.MAX_VALUE)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniciarActionPerformed
        System.out.println("¡Botón presionado! Intentando arrancar el reloj...");

        if (simClock != null) {
            Thread hiloReloj = new Thread(simClock);
            hiloReloj.start();
            btnIniciar.setEnabled(false);
        } else {
            System.out.println("!!! ERROR: simClock es null. No se creó en el constructor.");
        }    }//GEN-LAST:event_btnIniciarActionPerformed

    private void randomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_randomActionPerformed
        System.out.println("¡Botón presionado! Arrancando hilo generador...");

        Thread hiloGenerador = new Thread(new Runnable() {
            @Override
            public void run() {
                for (int i = 0; i < 20; i++) {
                    try {
                        // Intentamos crear el proceso
                        System.out.println(">>> Intentando crear proceso " + i + "...");
                        Process newP = new Process();

                        // Intentamos configurarlo y encolarlo
                        newP.aperiodicProcess(false, scheduler.getReadyQueue(), scheduler.getPolitic());
                        System.out.println(">>> Proceso " + i + " encolado correctamente.");

                        // Actualizamos la tabla
                        updateReadyQueue(scheduler.getReadyQueue());

                        Thread.sleep(500);

                    } catch (Exception e) { // ¡ATRAPAMOS EL ERROR SILENCIOSO!
                        System.err.println("!!! ERROR FATAL creando el proceso " + i + " !!!");
                        e.printStackTrace(); // Esto nos dirá la línea exacta del fallo
                        break; // Abortamos el bucle para no lanzar 20 errores seguidos
                    }
                }
                System.out.println("¡El hilo generador terminó!");
            }
        });

        hiloGenerador.start();
    }//GEN-LAST:event_randomActionPerformed

    /**
     * @param args the command line arguments
     */
    public void log(String mensaje) {
        SwingUtilities.invokeLater(() -> {
            txtConsola.append(mensaje + "\n");
            // Auto-scroll hacia abajo
            txtConsola.setCaretPosition(txtConsola.getDocument().getLength());
        });
    }

    // 2. Actualizar el Reloj y el CPU
// 1. Método para actualizar la Tabla de Listos (jTable1)
    public void updateReadyQueue(com.mycompany.sisoperativos.logic.Queue colaListos) {
        SwingUtilities.invokeLater(() -> {
            // Obtenemos el modelo de la tabla 1
            DefaultTableModel modelo = (DefaultTableModel) tablaListos.getModel();
            modelo.setRowCount(0); // Esto borra las filas anteriores para no duplicar

            if (colaListos != null) {
                // Empezamos desde el primero de la fila
                com.mycompany.sisoperativos.logic.PCB aux = colaListos.peek();

                // Recorremos la cola y vamos agregando filas
                while (aux != null) {
                    modelo.addRow(new Object[]{
                        aux.getId(),
                        aux.getDurationR(),
                        aux.getPriority(),
                        aux.getDeadlineR()
                    });
                    aux = aux.getNext(); // Pasamos al siguiente
                }
            }
        });
    }

    // 2. Método para actualizar la Tabla de Bloqueados (jTable2)
    public void updateBlockedQueue(com.mycompany.sisoperativos.logic.Queue colaBloqueados) {
        SwingUtilities.invokeLater(() -> {
            // Obtenemos el modelo de la tabla 2
            DefaultTableModel modelo = (DefaultTableModel) tablaBloqueados.getModel();
            modelo.setRowCount(0);

            if (colaBloqueados != null) {
                com.mycompany.sisoperativos.logic.PCB aux = colaBloqueados.peek();
                while (aux != null) {
                    modelo.addRow(new Object[]{
                        aux.getId(),
                        aux.getDurationR(),
                        aux.getPriority(),
                        aux.getDeadlineR()
                    });
                    aux = aux.getNext();
                }
            }
        });
    }
    
    // Método para actualizar la Tabla de Finalizados (jTable nueva)
    public void updateFinishedQueue(com.mycompany.sisoperativos.logic.Queue colaFinalizados) {
        SwingUtilities.invokeLater(() -> {
            // 1. Verificamos que la tabla exista para evitar errores
            if (tablaSalida== null) {
                System.err.println("Advertencia: tablaFinalizados no existe en la interfaz.");
                return;
            }

            // 2. Obtenemos el modelo de la tabla y la limpiamos
            DefaultTableModel modelo = (DefaultTableModel) tablaSalida.getModel();
            modelo.setRowCount(0); // Esto borra las filas anteriores para no duplicar datos

            // 3. Recorremos la cola de finalizados si no está vacía
            if (colaFinalizados != null) {
                com.mycompany.sisoperativos.logic.PCB aux = colaFinalizados.peek();

                while (aux != null) {
                    // Agregamos una nueva fila por cada proceso terminado
                    modelo.addRow(new Object[]{
                        aux.getId(),
                        aux.getDurationR(), // Si terminó bien será 0. Si murió por deadline, será > 0
                        aux.getPriority(),
                        aux.getDeadlineR()
                    });
                    
                    // Pasamos al siguiente nodo en la cola
                    aux = aux.getNext(); 
                }
            }
        });
    }

    // 3. Método para actualizar el CPU (Las etiquetas del medio)
    public void updateStatus(int ciclo, com.mycompany.sisoperativos.logic.PCB current) {
        SwingUtilities.invokeLater(() -> {
            lblReloj.setText("Ciclo Actual: " + ciclo);

            if (current != null) {
                // NOTA: Cambia jLabel1, jLabel2, jLabel3 por los nombres de tus textos celestes
                txtCpuId.setText("ID Ejecutando: " + current.getId());
                txtCpuRem.setText("Tiempo Restante: " + current.getDurationR());
                txtCpuPriority.setText("Prioridad: " + current.getPriority());
                txtCpuDL.setText("Deadline: "+ current.getDeadlineR());
            } else {
                txtCpuId.setText("CPU VACÍO");
                txtCpuRem.setText("-");
                txtCpuPriority.setText("-");
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIniciar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel lblReloj;
    private javax.swing.JButton random;
    private javax.swing.JTable tablaBloqueados;
    private javax.swing.JTable tablaListos;
    private javax.swing.JTable tablaSalida;
    private javax.swing.JTextArea txtConsola;
    private javax.swing.JLabel txtCpuDL;
    private javax.swing.JLabel txtCpuId;
    private javax.swing.JLabel txtCpuPriority;
    private javax.swing.JLabel txtCpuRem;
    // End of variables declaration//GEN-END:variables

}
