/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.sisoperativos.gui;

import javax.swing.*;
import java.awt.*;

/**
 *
 * @author gabri
 */
public class MonitorWindow extends javax.swing.JFrame {

    private CpuChart chart;
    private JLabel lblPorcentaje;

    /**
     * Creates new form MonitorWindow
     */
    public MonitorWindow() {
        setTitle("Monitor de Utilización CPU");
        setSize(450, 300);
        setLayout(new BorderLayout());
        setDefaultCloseOperation(JFrame.HIDE_ON_CLOSE); // Importante: no cierra el programa completo

        chart = new CpuChart();
        lblPorcentaje = new JLabel("Utilización: 0.0%", SwingConstants.CENTER);
        lblPorcentaje.setFont(new Font("Monospaced", Font.BOLD, 16));
        lblPorcentaje.setForeground(Color.CYAN);
        lblPorcentaje.setBackground(Color.BLACK);
        lblPorcentaje.setOpaque(true);

        add(chart, BorderLayout.CENTER);
        add(lblPorcentaje, BorderLayout.SOUTH);

        setLocationRelativeTo(null); // Centrar en pantalla
    }

    public void updateData(double value) {
        chart.addPoint(value);
        lblPorcentaje.setText(String.format("Utilización: %.1f%%", value));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
