/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.sisoperativos.gui;

import com.mycompany.sisoperativos.logic.Clock;
import com.mycompany.sisoperativos.logic.Scheduling;
import javax.swing.JLabel;
import javax.swing.Timer;

/**
 *
 * @author gabri
 */
public class VentanaMain extends javax.swing.JFrame {

// 1. Declaramos la variable del reloj y el Label manualmente
    private Clock reloj;
    private JLabel lblReloj;
    private JLabel lblCiclos;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VentanaMain.class.getName());

    /**
     * Creates new form VentanaMain
     */

    public VentanaMain(Clock reloj) {
        this.reloj = reloj;
        initComponents();

        // 2. Creamos y agregamos un Label simple para ver el reloj
        lblReloj = new JLabel("Ciclo actual: 0");
        lblReloj.setBounds(20, 20, 200, 30); // Posición básica
        lblCiclos = new JLabel("tiempo de ciclo: 0");
        lblCiclos.setBounds(50, 50, 200, 30); // Posición básica
        this.add(lblReloj);
        this.add(lblCiclos);

        // 3. Iniciamos el refresco visuals
        iniciarTimer();
    }

    private void iniciarTimer() {
        // Se ejecuta cada 100 milisegundos para actualizar el texto
        Timer timer = new Timer(100, (e) -> {
            if (reloj != null) {
                lblReloj.setText("Ciclo actual: " + reloj.getContadorCiclos());
                lblCiclos.setText("tiempo de ciclo: " + reloj.getDuracionCicloMs());

            }
        });
        timer.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (Exception ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        java.awt.EventQueue.invokeLater(() -> {
            // Creamos el reloj aquí
            Scheduling scheduler = new Scheduling();
            Clock miReloj = new Clock(1000, scheduler);

            // Iniciamos su hilo
            Thread hiloReloj = new Thread(miReloj);
            hiloReloj.start();

            // Se lo pasamos a la ventana
            new VentanaMain(miReloj).setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
